media:
  input: images
  output: /images

content:

  - name: posts
    label: Articles
    path: _articles
    type: collection

    filename: "{year}-{month}-{day}-{slug}.md"

    view:
      primary: title
      sort:
        - date
      default:
        sort: date
        order: desc

    fields:

      - name: title
        label: Title
        type: string
        required: true

      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - News
            - Film
            - TV
            - Reviews
            - Box Office
            - Awards
            - Trailers
            - Features

      - name: language
        label: Language
        type: select
        required: true
        options:
          values:
            - en
            - fa

      - name: date
        label: Publish Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd

      - name: updated
        label: Updated Date
        type: date
        required: false
        options:
          format: yyyy-MM-dd

      - name: summary
        label: Summary
        type: text
        required: true

      - name: people
        label: People
        type: string
        required: false
        description: Main people mentioned in the article

      - name: film
        label: Film
        type: string
        required: false

      - name: festival
        label: Festival
        type: string
        required: false

      - name: author
        label: Author
        type: string
        required: false

      - name: image
        label: Featured Image
        type: image

      - name: body
        label: Article
        type: rich-text
        required: true
