media:
  input: images
  output: /images

content:
  - name: posts
    label: Articles
    path: _articles
    type: collection

    fields:
      - name: title
        label: Title
        type: string

      - name: category
        label: Category
        type: select
        options:
          values:
            - News
            - Film
            - TV
            - Reviews
            - Box Office
            - Awards
            - Trailers
            - Features

      - name: language
        label: Language
        type: select
        options:
          values:
            - en
            - fa

      - name: date
        label: Publish Date
        type: date
        options:
          format: yyyy-MM-dd

      - name: summary
        label: Summary
        type: text

      - name: image
        label: Featured Image
        type: image

      - name: body
        label: Article
        type: rich-text
