title: CinemaDaily
description: English-language coverage of Iranian cinema, film, television and entertainment.
url: https://cinemadaily.ca
baseurl: ""

markdown: kramdown

collections:
  articles:
    output: true
    permalink: /articles/:name/

  people:
    output: true
    permalink: /people/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article

  - scope:
      path: ""
      type: people
    values:
      layout: person

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
